// SPDX-FileCopyrightText: 2025-2026 SPHARX Ltd.
// SPDX-License-Identifier: AGPL-3.0-or-later OR Apache-2.0

// T-18 分级（见 clippy.toml）：build.rs 的 expect 属构建期环境契约
// （OUT_DIR/CARGO_MANIFEST_DIR 由 cargo 保证，缺失即构建环境损坏），
// 非运行时生产路径，故整体放行；src/** 生产路径仍由 [lints.clippy] 强制。
#![allow(clippy::expect_used)]

// T-09 铁律（0.1.15 裁决 2026-09-10，方案 §4.7）：一切客户端功能走
// gateway，绝对禁止 TUI 直连 daemon / 运行时库。本脚本不再定位、链接
// 任何 agentrt C 侧静态库（memoryrovol FFI 已收回，记忆读写一律走
// gateway mem.* RPC；内置拼音 IME 直连一并收回，输入交回终端/OS 输入法）。
// TUI 运行时依赖仅剩：gateway HTTP/SSE 客户端 + 终端渲染栈。

use std::env;
use std::path::{Path, PathBuf};

/// W6 构建期门禁（T-10 推广）：TUI 允许静态链接的库集合。
///
/// T-09 收紧后为空集——任何 `assert_allowed_lib` 调用都会 panic，
/// 即"TUI 禁止链接任何运行时库"由机器强制而非约定保证。本闸门保留
/// 为铁律的机械化守卫：未来若确有新增链接需求，必须先经显式架构评审
/// 扩充此集合（见 0.1.15 方案 §4.6/§4.7 T-09/T-10），不允许绕过。
const ALLOWED_STATIC_LIBS: &[&str] = &[];

#[allow(dead_code)] // T-09 后无链接者；空集即任何调用都阻断（fail-closed 守卫）
fn assert_allowed_lib(name: &str) {
    if !ALLOWED_STATIC_LIBS.contains(&name) {
        panic!(
            "agentrt-tui 构建门禁（W6/T-09）：禁止链接非白名单静态库 `{}`。\n\
             允许集：{:?}。TUI 只许 gateway HTTP/SSE 客户端 + 渲染栈，\n\
             不得链入 agentrt daemon/runtime 任何内部库。",
            name, ALLOWED_STATIC_LIBS
        );
    }
}

fn main() {
    // ime_linked cfg 声明保留（src/ime.rs 等处以 all(feature, ime_linked)
    // 双门控 fail-closed 休眠）；mr_linked 随 T-09 FFI 收回一并移除。
    println!("cargo:rustc-check-cfg=cfg(ime_linked)");

    // 版本号 SSoT（2.6.2 Unify Design）：单一来源为 agentrt/VERSION 文件。
    // CI 布局（release 兄弟仓克隆：agent-workload/sdk/tui 与 agentrt/ 非
    // 邻接）下伞仓相对路径 ../../agentrt/VERSION 不存在，故支持
    // AIRY_RT_VERSION_FILE env 显式注入（build-tui.sh / release.yml 导出）；
    // 读取失败时降级 CARGO_PKG_VERSION。
    let version = std::env::var("AIRY_RT_VERSION_FILE")
        .ok()
        .and_then(|p| std::fs::read_to_string(p).ok())
        .or_else(|| {
            std::fs::read_to_string(Path::new(env!("CARGO_MANIFEST_DIR")).join(
                "../../agentrt/VERSION",
            ))
            .ok()
        })
        .map(|s| s.trim().to_string())
        .filter(|s| !s.is_empty())
        .unwrap_or_else(|| env!("CARGO_PKG_VERSION").to_string());
    if let Ok(vf) = std::env::var("AIRY_RT_VERSION_FILE") {
        println!("cargo:rerun-if-changed={vf}");
    }
    println!("cargo:rerun-if-changed=../../agentrt/VERSION");
    println!("cargo:rerun-if-changed=build.rs");
    println!("cargo:rustc-env=AIRY_RT_VERSION={version}");

    // 0.1.9 M5 W1：agent.run_stream v1 事件协议常量生成（SSoT）。
    // 唯一权威为 agentrt commons/include/airy_run_stream.h，本 crate 经
    // include!(OUT_DIR/run_stream_gen.rs) 共引，禁止手写 wire 键名字面量
    // （与 sdk-rust/src/run_stream.rs 同一机制，见方案 §2.4.4）。
    println!("cargo:rerun-if-env-changed=AGENTRT_TUI_RUN_STREAM_H");
    let rs_header = locate_run_stream_header();
    println!("cargo:rerun-if-changed={}", rs_header.display());
    let rs_content = std::fs::read_to_string(&rs_header).unwrap_or_else(|e| {
        panic!(
            "run_stream schema header unreadable: {} ({})",
            rs_header.display(),
            e
        )
    });
    let rs_gen = generate_run_stream_consts(&rs_content);
    if rs_gen.is_empty() {
        panic!(
            "run_stream schema header parsed zero AIRY_RS_* macros: {}",
            rs_header.display()
        );
    }
    let rs_out = PathBuf::from(env::var("OUT_DIR").expect("OUT_DIR not set"));
    std::fs::write(rs_out.join("run_stream_gen.rs"), rs_gen)
        .expect("failed to write run_stream_gen.rs");
}

/// 定位 airy_run_stream.h（v1 协议 schema SSoT）：优先 env
/// AGENTRT_TUI_RUN_STREAM_H，否则 monorepo 默认布局（tui 上溯两级到
/// agent-workload 后进入 agentrt/）。缺失即构建失败（fail-closed）。
fn locate_run_stream_header() -> PathBuf {
    if let Ok(path) = env::var("AGENTRT_TUI_RUN_STREAM_H") {
        let p = PathBuf::from(&path);
        if p.is_file() {
            return p;
        }
        panic!("AGENTRT_TUI_RUN_STREAM_H set but not a file: {path}");
    }
    let manifest = env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR not set");
    let candidate = Path::new(&manifest).join("../../agentrt/commons/include/airy_run_stream.h");
    if candidate.is_file() {
        return candidate;
    }
    panic!(
        "run_stream schema header not found (tried {}). \
         Set AGENTRT_TUI_RUN_STREAM_H to the airy_run_stream.h path.",
        candidate.display()
    );
}

/// 解析 #define AIRY_RS_* 宏并生成 Rust 常量（统一收纳于 gen 子模块）。
/// 与 sdk-rust/build.rs 逻辑对齐，保证编码端/解码端字段一致。
fn generate_run_stream_consts(content: &str) -> String {
    let mut out = String::new();
    out.push_str("// @generated by tui/build.rs from agentrt commons/include/airy_run_stream.h\n");
    out.push_str("// DO NOT EDIT. 字段键/事件类型常量以 C 侧 schema 为唯一权威（SSoT）。\n\n");
    out.push_str("pub mod gen {\n");
    for line in content.lines() {
        let line = line.trim();
        let Some(rest) = line.strip_prefix("#define ") else {
            continue;
        };
        let mut parts = rest.splitn(2, char::is_whitespace);
        let name = parts.next().unwrap_or("");
        let value = parts.next().unwrap_or("").trim();
        if !name.starts_with("AIRY_RS_") || value.is_empty() {
            continue;
        }
        if value.starts_with('"') && value.ends_with('"') {
            out.push_str(&format!("    pub const {name}: &str = {value};\n"));
        } else if value.chars().all(|c| c.is_ascii_digit()) {
            out.push_str(&format!("    pub const {name}: i64 = {value};\n"));
        }
    }
    out.push_str("}\n");
    out
}
